### ISSUE TITLE
Schutzrechte Dritter

### ISSUE THREAD

**Issue by codedust** [codeforcologne/OpenDataWizzard#2]
In der ersten Frage heißt es:

> Daten können jedoch auch anderen Schutzrechten unterliegen:
> - Personenbezogene Daten
> - Betriebsgeheimnisse
> - Verträge
> - ...

Die Nennung von "Verträgen" ist hier ggf. etwas zu pauschal. Verträge können die Datennutzung nur auf Grundlage der später ohnehin abgefragten (Datenbank-)urheberrechte eingeschränken.

Daher würde ich vorschlagen, zu jedem aufgeführten Punkt auch die jeweilige Rechtsgrundlage zunennen:

> Daten können jedoch auch anderen Schutzrechten unterliegen:
> - [Urheberpersönlichkeitsrechte](https://www.bpb.de/themen/recht-justiz/persoenlichkeitsrechte/244852/das-urheberpersoenlichkeitsrecht/) bei personenbezogenen Daten
> - Rechte des Beschäftigtendatenschutz
> - [Betriebs- und Geschäftsgeheimnisse](https://de.wikipedia.org/wiki/Betriebs-_und_Gesch%C3%A4ftsgeheimnis)
> - [Verschwiegenheitsvereinbarungen / Geheimhaltungsverträge](https://de.wikipedia.org/wiki/Geheimhaltungsvertrag)
> - ...

**Comment by OpenDEM** [comment]
Ergänzung der Rechtsgrundlagen bei anderen Schutzrechten. Die Urheberpersönlichkeitsrechte bezüglich des Urheberrechts habe ich nicht rein genommen, da diese ja explizit vorher erwähnt werden.
